config/routes.rb
Rails.application.routes.draw do
  root to: 'form#index'
  resources :form, only: [:index, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message
    attribute :nickname,  :captcha  => true
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "Contact Form Inquiry",
        :to => "hanspreeker@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def default_url_options
        { host: ENV["DOMAIN"] || "localhost:3000" }
    end
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  def index
    @contact = Form.new(params[:form])
  end

  def create
    @contact = Form.new(params[:form])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Form object for cleared form
        @contact = Form.new
        format.html { render root_path }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render root_path }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end

    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/form/create.js.erb
console.log("This is the create.js.erb file");

$('#contact').html("<%= j render 'shared/contact_form' %>");
$('#flash-message').html("<%= j render 'shared/flash' %>").delay(3000).fadeOut(4000);

app/views/form/index.html.erb
<div id="top-container">

    <div class="text-container">
        <h1>Hi I'm Hans Preeker!</h1>
            A enthousiastic developer who loves to create awesome experiences for others.
            </br>
            As I was planning on making a career change from Hospitality to IT in 2021,
            then corona came in 2020 and I decided that this was going to be the year to learn to code.
            </br>
            I followed the coding bootcamp at Le Wagon in Amsterdam. My current stack is Ruby on Rails, Javascript ES6, HTML5, CSS and MySQL.
            </br>

        <h2>Flying IT Dutchman</h2>
            Love traveling and would fly/move anywhere in the world for interesting jobs/projects.
    </div>

    <%= image_tag('Hans2.jpg', :class => "profile_img") %>
    
</div>

<div id="project-container">
    <h2>Projects</h2>
        The following projects is what I have worked on in the projectgroups of Le Wagon.
        </br>
        </br>
        <div class="card-container">

                <div class="img-container">
                    <%= link_to "https://www.moveablefeasts.club", target: "_blank" do %>
                    <%= image_tag "moveable_feasts.gif", border: 0, :class => "card-img" %>
                    <div class="middle">
                        <div class="text">
                        <h2>Movable Feasts</h2>
                        A platform for connecting people over a nice meal and/or drinks/cocktails.
                        
                        </div>
                    </div>
                    <% end  %>
                </div>

                <div class="img-container">
                    <%= link_to "http://bookbookborrow.herokuapp.com/", target: "_blank" do %>
                    <%= image_tag "bookborrow.png", border: 0, :class => "card-img" %>
                    <div class="middle">
                        <div class="text">
                        <h2>Bookborrow</h2>
                         For people to borrow and lend books to people in their neighborhoods. A digital library for people who don't like to go through the actual library.
                        </div>
                    </div>
                    <% end %>
                </div>
        </div>
</div>

<div id="form-container">
    <h2>Let's get in touch!</h2>
    <%= render 'shared/contact_form' %>
    </br>
    <h2>OR</h2>

        <%= mail_to "hans_preeker@hotmail.com", :class => "mail_to" do %>
        <%= image_tag 'envelope.png', :class => "email-img" %>
                <p class="email-text">Email me</p>

        <% end %>

</div>

<div class="footer-container">

    <h2 class="footer-text">Business Socials</h2>

        <ul class="list-inline">
            <li>
                <a href="https://www.linkedin.com/in/hans-preeker-88271147/" target="_blank">
               <%= image_tag 'iconfinder_linkedin_386655.png', :class => "icon" %>
                </a>
            </li>
            <li>
                <a href="https://github.com/Ravemaster8" target="_blank">
                <%= image_tag 'octocat.png', :class => "icon" %></a>
            </li>
        </ul>
        </br>

    <h2 class="footer-text">Language Stack</h2>
        </br>
        <ul class="list-inline">
            <li>
                <%= image_tag 'html5.png', :class => "icon" %>
            </li>
            <li>
                <%= image_tag 'css.png', :class => "icon" %>
            </li>
            <li>
                <%= image_tag 'javascript.png', :class => "icon" %>
            </li>
            <li>
                <%= image_tag 'rails.png', :class => "icon" %>
            </li>
            <li>
                <%= image_tag 'sql.png', :class => "icon" %>
            </li>
            <li>
                <%= image_tag 'heroku.png', :class => "icon" %>
            </li>
        </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hans's Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <%= render 'shared/navbar' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="top-container">

    <div class="text-container">
        <h1>Hi I'm Hans Preeker!</h1>
            A enthousiastic developer who loves to create awesome experiences for others.
            </br>
            As I was planning on making a career change from Hospitality to IT in 2021,
            then corona came in 2020 and I decided that this was going to be the year to learn to code.
            </br>
            I followed the coding bootcamp at Le Wagon in Amsterdam. My current stack is Ruby on Rails, Javascript ES6, HTML5, CSS and MySQL.
            </br>
    </div>

    <%= image_tag('Hans2.jpg', :class => "profile_img") %>
</div>

<div class="container">
    <h2>Projects</h2>
        The following projects is what I have worked on in the projectgroups of Le Wagon.
        </br>
        </br>
        <div class="card-container">

                <div class="img-container">
                    <%= link_to "https://www.moveablefeasts.club", target: "_blank" do %>
                    <%= image_tag "moveable_feasts.gif", border: 0, :class => "card-img" %>
                    <div class="middle">
                        <div class="text">Movable Feasts</div>
                    </div>
                    <% end  %>
                </div>

                <div class="img-container">
                    <%= link_to "http://bookbookborrow.herokuapp.com/", target: "_blank" do %>
                    <%= image_tag "bookborrow.png", border: 0, :class => "card-img" %>
                    <div class="middle">
                        <div class="text">Bookborrow</div>
                    </div>
                    <% end %>
                </div>
            
        </div>
</div>

<div class="container">
    <h2>Flying IT Dutchman</h2>
        <p>Love traveling and would fly/move anywhere in the world for interesting jobs/projects.</p>
</div>

<div class="container">
    <h2>Follow me!</h2>
        <ul class="list-inline">
            <li>
                <a href="https://www.linkedin.com/in/hans-preeker-88271147/" target="_blank">
               <%= image_tag 'iconfinder_linkedin_386655.png', :class => "icon" %>
                </a>
            </li>
            <li>
                <a href="https://github.com/Ravemaster8" target="_blank">
                <%= image_tag 'octocat.png', :class => "icon" %></a>
            </li>
        </ul>
</div>

app/views/shared/_contact_form.html.erb
<%= form_for @contact, url: form_index_path, remote: true do |f| %>
  <div>
      <%= f.text_field  :name, required: true, class: "contact-form-text-area", placeholder: "Name" %></br>

      <%= f.text_field :email, required: true, class: "contact-form-text-area", placeholder: "E-mail" %></br>

      <%= f.text_area :message, required: true, class: "contact-form-text-area", id: "contact-form-message", placeholder: "Your message"%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

    <%= f.submit 'SUBMIT MESSAGE', class: "contact-form-button" %>
  </div>
<% end %>

  <div>
    <%= render 'shared/flash' %>
  </div>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <%= link_to 'Personal', root_path(:anchor => "top-container"), :id => "navbar_links" %>
    <%= link_to 'Projects', root_path(:anchor => "project-container"), :id => "navbar_links" %>
    <%= link_to 'Contact', root_path(:anchor => "form-container"), :id => "navbar_links" %>
</div>